Repository PyTorchLightning/pytorch-lightning-conference-seed, pull requests merged in 2020-08, with the labels that each got.

#9 Update with Data Module and Loggers
  .gitignore
  requirements.txt
  src/research_mnist/mnist.py
  src/research_mnist/mnist_data_module.py
  src/research_mnist/mnist_trainer.py
Labels: enhancement

#8 update project url
  HOWTO.md
Labels: documentation

#10 prune seed
  HOWTO.md
  README.md
  research_mnist/README.md
  research_mnist/__init__.py
  research_mnist/mnist_data_module.py
  research_mnist/mnist_trainer.py
  research_mnist/simplest_mnist.py
  setup.py
  src/README.md
  src/production_mnist/README.md
  src/production_mnist/__init__.py
  src/production_mnist/mnist.py
  src/research_mnist/README.md
  src/research_mnist/__init__.py
  src/research_mnist/mnist_trainer.py
  src/simplest_mnist.py
Labels: enhancement

#11 adding CI
  .codecov.yml
  .github/workflows/ci-testing.yml
  .github/workflows/code-format.yml
  .pep8speaks.yml
  requirements.txt
  research_mnist/mnist_data_module.py
  research_mnist/mnist_trainer.py
  research_mnist/simplest_mnist.py
  setup.cfg
  setup.py
  tests/requirements.txt
  tests/test_scripts.py
Labels: enhancement

#12 add Badges
  .github/stale.yml
  .github/workflows/ci-testing.yml
  .github/workflows/greetings.yml
  README.md
Labels: documentation, enhancement
